import api from './api';

/**
 * Service to interact with the AI Model's database
 * This fetches the alerts, images, and metadata populated by the Python/AI model
 */
export const modelService = {
  // Fetch latest alerts generated by the AI model
  getLatestAlerts: async (limit = 10) => {
    try {
      const response = await api.get(`/model/alerts?limit=${limit}`);
      return response.data;
    } catch (error) {
      console.warn('Model alerts unavailable (model may be offline):', error.message);
      return { alerts: [] }; // Return empty instead of throwing
    }
  },

  // Fetch specific incident details including base64/URL of the captured frame
  getIncidentDetails: async (incidentId) => {
    try {
      const response = await api.get(`/model/incidents/${incidentId}`);
      return response.data;
    } catch (error) {
      console.error('Error fetching incident details:', error);
      throw error;
    }
  },

  // Fetch the latest processed frames from all active cameras
  getLatestCaptures: async () => {
    try {
      const response = await api.get('/model/captures/latest');
      return response.data;
    } catch (error) {
      console.error('Error fetching latest captures:', error);
      throw error;
    }
  }
};

export default modelService;
